#!/bin/bash

if [ -e /var/lib/rancher/conf/docker ]; then
    source /var/lib/rancher/conf/docker
fi

while [ ! -e /run/console-done ]; do
    sleep 1
done

exec /usr/bin/dockerlaunch /usr/bin/docker "$@" $DOCKER_OPTS >/var/log/docker.log 2>&1
