#!/bin/bash
set -e

BASEDIR=$(cd $(dirname $0)/..; pwd)

cd $(dirname $0)

source ./version
VERSION=${VERSION:?"VERSION not set"}

cd ${BASEDIR}

for i in src/docker/[0-9]*; do
    tag="rancher/os-$(echo $i | cut -f2 -d-)"
    echo Building $tag
    if [ -x ${i}/.prebuild.sh ]; then
        ${i}/.prebuild.sh;
    fi
    docker build -t ${tag} $i
    docker tag -f ${tag} ${tag}:${VERSION}
done
