#!/bin/bash
set -e

cd $(dirname $0)/..

source scripts/version
VERSION=${VERSION:?"VERSION not set"}

## FIXME BROKEN!

for i in scripts/extraimages/[0-9]*; do
    tag=$(echo $i | cut -f2 -d-):${VERSION}
    echo Building $tag
    docker build -t rancher/$tag -f $i .
done
