#!/bin/bash
set -e

VERSION=${VERSION:?"VERSION not set"}

BASE_CONTAINER=$(docker create rancher/dind:v0.1.0)

function cleanup {
    docker rm -v ${BASE_CONTAINER}
    echo "Bye! You've been trapped :D"
}
trap cleanup EXIT

cd $(dirname $0)/..

source scripts/build-common

BUILD=./src/docker/00-base/build
mkdir -p ${BUILD}

echo Extracting ${ARTIFACTS}/os-base.tar.xz
tar xJf ${ARTIFACTS}/os-base.tar.xz -C ${BUILD}

docker cp ${BASE_CONTAINER}:/etc/ssl/certs/ca-certificates.crt src/docker/05-docker/build

for i in src/docker/[0-9]*; do
    tag="rancher/os-$(echo $i | cut -f2 -d-)"
    echo Building $tag
    docker build -t ${tag} $i
    docker tag -f ${tag} ${tag}:${VERSION}
done
