#!/bin/bash
set -e

export ARCH=${ARCH:-"amd64"}

cd $(dirname $0)/..

DO_PUSH="$1"

set -a
. build.conf
. build.conf.${ARCH}
[ "${ARCH}" == "amd64" ] || . ./.docker-env.${ARCH}
set +a

SUFFIX=""
[ "${ARCH}" == "amd64" ] || SUFFIX="_${ARCH}"

if [ "${DO_PUSH}" == "--push" ]; then
    for i in src/docker/[0-9]*; do
        name="os-$(echo ${i} | cut -f2 -d-)"
        tag="${OS_IMAGES_ROOT}/${name}:${VERSION}${SUFFIX}"
        echo Pushing ${tag}
        docker push ${tag} || :
    done
else
    for i in src/docker/[0-9]*; do
        name="os-$(echo ${i} | cut -f2 -d-)"
        tag="${OS_IMAGES_ROOT}/${name}:${VERSION}${SUFFIX}"
        echo Building ${tag}
        if [ -x ${i}/.prebuild.sh ]; then
            if ${i}/.prebuild.sh; then
                docker build -t rancher/${name} ${i}
                docker tag rancher/${name} ${tag}
            elif [ "$?" != "42" ]; then
                exit 1
            else
                echo "WARN: Skipping ${tag}"
            fi
        else
            docker build -t rancher/${name} ${i}
            docker tag rancher/${name} ${tag}
        fi
    done
fi
