#!/bin/bash
set -e

: ${ARTIFACTS:=$(pwd)/assets}

check()
{
    local hash=$1
    local file=$2

    if [ ! -e "$file" ]; then
        return 1
    fi

    if [ "$hash" = dev ]; then
        return 0
    fi

    CURRENT=$(sha1sum $file | awk '{print $1}')

    [ "$hash" = "$CURRENT" ]
}

download()
{
    mkdir -p ${ARTIFACTS}

    local url=$2
    local file=${ARTIFACTS}/$(basename $2)
    local hash=$1

    if [ "$3" != "" ]; then
        file=${ARTIFACTS}/$3
    fi

    if ! check $hash $file; then
        echo Downloading $url to $file
        curl -sL $url > $file
    fi

    if ! check $hash $file; then
        echo "ERROR: $file does not match checksum $hash, got $CURRENT" 1>&2
        return 1
    fi
}
