#!/bin/bash
set -ex

cd $(dirname $0)/..

export DOCKER_IMAGE=${DOCKER_IMAGE:=rancher-os-images-build}
export DOCKER_BASE=rancher/dind:v0.1.0

source scripts/build-common

DOCKER_FILE=$(pwd)/.dockerfile

generate_images()
{
    IMAGE_ID=$(docker images --no-trunc -q ${DOCKER_IMAGE})

    if [ -e ${BUILD}/${IMAGE_ID} ]; then
        DOCKER_BASE=$(<${BUILD}/${IMAGE_ID})
    else
        echo Running: docker run -d --privileged ${DOCKER_IMAGE} /source/scripts/build-images
        CID=$(docker run -d --privileged ${DOCKER_IMAGE} /source/scripts/build-images)
        docker logs -f ${CID} &
        trap "docker rm -f ${CID}" exit
        [ "$(docker wait $CID)" == 0 ]
        DOCKER_BASE=$(docker commit $CID)

        echo ${DOCKER_BASE} > ${BUILD}/${IMAGE_ID}
    fi
}

run ./scripts/bootstrap
run --assets ./scripts/build-common --assets ./assets ./scripts/download
run --assets ./scripts/dockerimages --assets ./scripts/build-images
run --assets ./scripts/install
finish

generate_images
